agent:
  max_retries: 10
  script_url: https://raw.githubusercontent.com/angristan/openvpn-install/master/openvpn-install.sh
  sleep_seconds: 3

openvpn:
  path:
    darwin: openvpn
    linux: openvpn
    win32: C:\Program Files\OpenVPN\bin\openvpn-gui.exe

providers:
  linode:
    image: linode/ubuntu20.04
    key: <LINODE_API_KEY>
    type_slug: g6-dedicated-2
