agent:
  script_url: https://raw.githubusercontent.com/angristan/openvpn-install/master/openvpn-install.sh

authorized_keys:
  - <PUBLIC_SSH_KEY>
  - <PUBLIC_SSH_KEY>

providers:
  linode:
    key: <LINODE_API_KEY>
    type_slug: g6-dedicated-2
