agent:
  script_url: https://raw.githubusercontent.com/angristan/openvpn-install/master/openvpn-install.sh
  ssh_key_path: ~/.ssh/id_ed25519

authorized_keys:
  - <PUBLIC_SSH_KEY>
  - <PUBLIC_SSH_KEY>

providers:
  linode:
    image: linode/ubuntu22.04
    key: <LINODE_API_KEY>
    type_slug: g6-dedicated-2
